/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TxRouteImport } from './routes/tx'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaviconRouteImport } from './routes/favicon'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BetaAccessRouteImport } from './routes/beta-access'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as TxTransactionIdRouteImport } from './routes/tx.$transactionId'
import { Route as FxQuoteRouteImport } from './routes/fx.quote'
import { Route as FxExecuteRouteImport } from './routes/fx.execute'
import { Route as DocsSecurityRouteImport } from './routes/docs.security'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'
import { Route as DocsOverviewRouteImport } from './routes/docs.overview'
import { Route as DocsIntegrationRouteImport } from './routes/docs.integration'
import { Route as DocsFaqRouteImport } from './routes/docs.faq'
import { Route as DocsConceptsRouteImport } from './routes/docs.concepts'
import { Route as CircleStablefxRouteImport } from './routes/circle.stablefx'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminInvitesRouteImport } from './routes/admin.invites'
import { Route as AccountWalletsRouteImport } from './routes/account.wallets'
import { Route as AccountPreferencesRouteImport } from './routes/account.preferences'
import { Route as AccountHistoryRouteImport } from './routes/account.history'
import { Route as ApiBetaValidateCodeRouteImport } from './routes/api.beta.validate-code'
import { Route as ApiBetaSessionRouteImport } from './routes/api.beta.session'
import { Route as ApiBetaAdminUsersRouteImport } from './routes/api.beta.admin.users'
import { Route as ApiBetaAdminCodesRouteImport } from './routes/api.beta.admin.codes'
import { Route as ApiBetaAdminAuthRouteImport } from './routes/api.beta.admin.auth'

const TxRoute = TxRouteImport.update({
  id: '/tx',
  path: '/tx',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconRoute = FaviconRouteImport.update({
  id: '/favicon',
  path: '/favicon',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaAccessRoute = BetaAccessRouteImport.update({
  id: '/beta-access',
  path: '/beta-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const TxTransactionIdRoute = TxTransactionIdRouteImport.update({
  id: '/$transactionId',
  path: '/$transactionId',
  getParentRoute: () => TxRoute,
} as any)
const FxQuoteRoute = FxQuoteRouteImport.update({
  id: '/fx/quote',
  path: '/fx/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const FxExecuteRoute = FxExecuteRouteImport.update({
  id: '/fx/execute',
  path: '/fx/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)
const DocsOverviewRoute = DocsOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DocsRoute,
} as any)
const DocsIntegrationRoute = DocsIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsRoute = DocsConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => DocsRoute,
} as any)
const CircleStablefxRoute = CircleStablefxRouteImport.update({
  id: '/circle/stablefx',
  path: '/circle/stablefx',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWalletsRoute = AccountWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPreferencesRoute = AccountPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AccountRoute,
} as any)
const AccountHistoryRoute = AccountHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AccountRoute,
} as any)
const ApiBetaValidateCodeRoute = ApiBetaValidateCodeRouteImport.update({
  id: '/api/beta/validate-code',
  path: '/api/beta/validate-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetaSessionRoute = ApiBetaSessionRouteImport.update({
  id: '/api/beta/session',
  path: '/api/beta/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetaAdminUsersRoute = ApiBetaAdminUsersRouteImport.update({
  id: '/api/beta/admin/users',
  path: '/api/beta/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetaAdminCodesRoute = ApiBetaAdminCodesRouteImport.update({
  id: '/api/beta/admin/codes',
  path: '/api/beta/admin/codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetaAdminAuthRoute = ApiBetaAdminAuthRouteImport.update({
  id: '/api/beta/admin/auth',
  path: '/api/beta/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/beta-access': typeof BetaAccessRoute
  '/docs': typeof DocsRouteWithChildren
  '/favicon': typeof FaviconRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/stats': typeof StatsRoute
  '/tx': typeof TxRouteWithChildren
  '/account/history': typeof AccountHistoryRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/circle/stablefx': typeof CircleStablefxRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/integration': typeof DocsIntegrationRoute
  '/docs/overview': typeof DocsOverviewRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/security': typeof DocsSecurityRoute
  '/fx/execute': typeof FxExecuteRoute
  '/fx/quote': typeof FxQuoteRoute
  '/tx/$transactionId': typeof TxTransactionIdRoute
  '/account/': typeof AccountIndexRoute
  '/api/beta/session': typeof ApiBetaSessionRoute
  '/api/beta/validate-code': typeof ApiBetaValidateCodeRoute
  '/api/beta/admin/auth': typeof ApiBetaAdminAuthRoute
  '/api/beta/admin/codes': typeof ApiBetaAdminCodesRoute
  '/api/beta/admin/users': typeof ApiBetaAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/beta-access': typeof BetaAccessRoute
  '/docs': typeof DocsRouteWithChildren
  '/favicon': typeof FaviconRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/stats': typeof StatsRoute
  '/tx': typeof TxRouteWithChildren
  '/account/history': typeof AccountHistoryRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/circle/stablefx': typeof CircleStablefxRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/integration': typeof DocsIntegrationRoute
  '/docs/overview': typeof DocsOverviewRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/security': typeof DocsSecurityRoute
  '/fx/execute': typeof FxExecuteRoute
  '/fx/quote': typeof FxQuoteRoute
  '/tx/$transactionId': typeof TxTransactionIdRoute
  '/account': typeof AccountIndexRoute
  '/api/beta/session': typeof ApiBetaSessionRoute
  '/api/beta/validate-code': typeof ApiBetaValidateCodeRoute
  '/api/beta/admin/auth': typeof ApiBetaAdminAuthRoute
  '/api/beta/admin/codes': typeof ApiBetaAdminCodesRoute
  '/api/beta/admin/users': typeof ApiBetaAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/beta-access': typeof BetaAccessRoute
  '/docs': typeof DocsRouteWithChildren
  '/favicon': typeof FaviconRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/stats': typeof StatsRoute
  '/tx': typeof TxRouteWithChildren
  '/account/history': typeof AccountHistoryRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/circle/stablefx': typeof CircleStablefxRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/integration': typeof DocsIntegrationRoute
  '/docs/overview': typeof DocsOverviewRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/security': typeof DocsSecurityRoute
  '/fx/execute': typeof FxExecuteRoute
  '/fx/quote': typeof FxQuoteRoute
  '/tx/$transactionId': typeof TxTransactionIdRoute
  '/account/': typeof AccountIndexRoute
  '/api/beta/session': typeof ApiBetaSessionRoute
  '/api/beta/validate-code': typeof ApiBetaValidateCodeRoute
  '/api/beta/admin/auth': typeof ApiBetaAdminAuthRoute
  '/api/beta/admin/codes': typeof ApiBetaAdminCodesRoute
  '/api/beta/admin/users': typeof ApiBetaAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/analytics'
    | '/beta-access'
    | '/docs'
    | '/favicon'
    | '/login'
    | '/payment'
    | '/stats'
    | '/tx'
    | '/account/history'
    | '/account/preferences'
    | '/account/wallets'
    | '/admin/invites'
    | '/auth/callback'
    | '/circle/stablefx'
    | '/docs/concepts'
    | '/docs/faq'
    | '/docs/integration'
    | '/docs/overview'
    | '/docs/quickstart'
    | '/docs/security'
    | '/fx/execute'
    | '/fx/quote'
    | '/tx/$transactionId'
    | '/account/'
    | '/api/beta/session'
    | '/api/beta/validate-code'
    | '/api/beta/admin/auth'
    | '/api/beta/admin/codes'
    | '/api/beta/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/beta-access'
    | '/docs'
    | '/favicon'
    | '/login'
    | '/payment'
    | '/stats'
    | '/tx'
    | '/account/history'
    | '/account/preferences'
    | '/account/wallets'
    | '/admin/invites'
    | '/auth/callback'
    | '/circle/stablefx'
    | '/docs/concepts'
    | '/docs/faq'
    | '/docs/integration'
    | '/docs/overview'
    | '/docs/quickstart'
    | '/docs/security'
    | '/fx/execute'
    | '/fx/quote'
    | '/tx/$transactionId'
    | '/account'
    | '/api/beta/session'
    | '/api/beta/validate-code'
    | '/api/beta/admin/auth'
    | '/api/beta/admin/codes'
    | '/api/beta/admin/users'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/analytics'
    | '/beta-access'
    | '/docs'
    | '/favicon'
    | '/login'
    | '/payment'
    | '/stats'
    | '/tx'
    | '/account/history'
    | '/account/preferences'
    | '/account/wallets'
    | '/admin/invites'
    | '/auth/callback'
    | '/circle/stablefx'
    | '/docs/concepts'
    | '/docs/faq'
    | '/docs/integration'
    | '/docs/overview'
    | '/docs/quickstart'
    | '/docs/security'
    | '/fx/execute'
    | '/fx/quote'
    | '/tx/$transactionId'
    | '/account/'
    | '/api/beta/session'
    | '/api/beta/validate-code'
    | '/api/beta/admin/auth'
    | '/api/beta/admin/codes'
    | '/api/beta/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  BetaAccessRoute: typeof BetaAccessRoute
  DocsRoute: typeof DocsRouteWithChildren
  FaviconRoute: typeof FaviconRoute
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  StatsRoute: typeof StatsRoute
  TxRoute: typeof TxRouteWithChildren
  AdminInvitesRoute: typeof AdminInvitesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CircleStablefxRoute: typeof CircleStablefxRoute
  FxExecuteRoute: typeof FxExecuteRoute
  FxQuoteRoute: typeof FxQuoteRoute
  ApiBetaSessionRoute: typeof ApiBetaSessionRoute
  ApiBetaValidateCodeRoute: typeof ApiBetaValidateCodeRoute
  ApiBetaAdminAuthRoute: typeof ApiBetaAdminAuthRoute
  ApiBetaAdminCodesRoute: typeof ApiBetaAdminCodesRoute
  ApiBetaAdminUsersRoute: typeof ApiBetaAdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tx': {
      id: '/tx'
      path: '/tx'
      fullPath: '/tx'
      preLoaderRoute: typeof TxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon': {
      id: '/favicon'
      path: '/favicon'
      fullPath: '/favicon'
      preLoaderRoute: typeof FaviconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta-access': {
      id: '/beta-access'
      path: '/beta-access'
      fullPath: '/beta-access'
      preLoaderRoute: typeof BetaAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/tx/$transactionId': {
      id: '/tx/$transactionId'
      path: '/$transactionId'
      fullPath: '/tx/$transactionId'
      preLoaderRoute: typeof TxTransactionIdRouteImport
      parentRoute: typeof TxRoute
    }
    '/fx/quote': {
      id: '/fx/quote'
      path: '/fx/quote'
      fullPath: '/fx/quote'
      preLoaderRoute: typeof FxQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fx/execute': {
      id: '/fx/execute'
      path: '/fx/execute'
      fullPath: '/fx/execute'
      preLoaderRoute: typeof FxExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/security': {
      id: '/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsSecurityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/overview': {
      id: '/docs/overview'
      path: '/overview'
      fullPath: '/docs/overview'
      preLoaderRoute: typeof DocsOverviewRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/integration': {
      id: '/docs/integration'
      path: '/integration'
      fullPath: '/docs/integration'
      preLoaderRoute: typeof DocsIntegrationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts': {
      id: '/docs/concepts'
      path: '/concepts'
      fullPath: '/docs/concepts'
      preLoaderRoute: typeof DocsConceptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/circle/stablefx': {
      id: '/circle/stablefx'
      path: '/circle/stablefx'
      fullPath: '/circle/stablefx'
      preLoaderRoute: typeof CircleStablefxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wallets': {
      id: '/account/wallets'
      path: '/wallets'
      fullPath: '/account/wallets'
      preLoaderRoute: typeof AccountWalletsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/preferences': {
      id: '/account/preferences'
      path: '/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof AccountPreferencesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/history': {
      id: '/account/history'
      path: '/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AccountHistoryRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/beta/validate-code': {
      id: '/api/beta/validate-code'
      path: '/api/beta/validate-code'
      fullPath: '/api/beta/validate-code'
      preLoaderRoute: typeof ApiBetaValidateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta/session': {
      id: '/api/beta/session'
      path: '/api/beta/session'
      fullPath: '/api/beta/session'
      preLoaderRoute: typeof ApiBetaSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta/admin/users': {
      id: '/api/beta/admin/users'
      path: '/api/beta/admin/users'
      fullPath: '/api/beta/admin/users'
      preLoaderRoute: typeof ApiBetaAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta/admin/codes': {
      id: '/api/beta/admin/codes'
      path: '/api/beta/admin/codes'
      fullPath: '/api/beta/admin/codes'
      preLoaderRoute: typeof ApiBetaAdminCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta/admin/auth': {
      id: '/api/beta/admin/auth'
      path: '/api/beta/admin/auth'
      fullPath: '/api/beta/admin/auth'
      preLoaderRoute: typeof ApiBetaAdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountHistoryRoute: typeof AccountHistoryRoute
  AccountPreferencesRoute: typeof AccountPreferencesRoute
  AccountWalletsRoute: typeof AccountWalletsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountHistoryRoute: AccountHistoryRoute,
  AccountPreferencesRoute: AccountPreferencesRoute,
  AccountWalletsRoute: AccountWalletsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface DocsRouteChildren {
  DocsConceptsRoute: typeof DocsConceptsRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsIntegrationRoute: typeof DocsIntegrationRoute
  DocsOverviewRoute: typeof DocsOverviewRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsSecurityRoute: typeof DocsSecurityRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsConceptsRoute: DocsConceptsRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsIntegrationRoute: DocsIntegrationRoute,
  DocsOverviewRoute: DocsOverviewRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsSecurityRoute: DocsSecurityRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface TxRouteChildren {
  TxTransactionIdRoute: typeof TxTransactionIdRoute
}

const TxRouteChildren: TxRouteChildren = {
  TxTransactionIdRoute: TxTransactionIdRoute,
}

const TxRouteWithChildren = TxRoute._addFileChildren(TxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  BetaAccessRoute: BetaAccessRoute,
  DocsRoute: DocsRouteWithChildren,
  FaviconRoute: FaviconRoute,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  StatsRoute: StatsRoute,
  TxRoute: TxRouteWithChildren,
  AdminInvitesRoute: AdminInvitesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CircleStablefxRoute: CircleStablefxRoute,
  FxExecuteRoute: FxExecuteRoute,
  FxQuoteRoute: FxQuoteRoute,
  ApiBetaSessionRoute: ApiBetaSessionRoute,
  ApiBetaValidateCodeRoute: ApiBetaValidateCodeRoute,
  ApiBetaAdminAuthRoute: ApiBetaAdminAuthRoute,
  ApiBetaAdminCodesRoute: ApiBetaAdminCodesRoute,
  ApiBetaAdminUsersRoute: ApiBetaAdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
