/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AccountWalletsRouteImport } from './routes/account.wallets'
import { Route as AccountPreferencesRouteImport } from './routes/account.preferences'
import { Route as AccountHistoryRouteImport } from './routes/account.history'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWalletsRoute = AccountWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPreferencesRoute = AccountPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AccountRoute,
} as any)
const AccountHistoryRoute = AccountHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/account/history'
    | '/account/preferences'
    | '/account/wallets'
    | '/auth/callback'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account/history'
    | '/account/preferences'
    | '/account/wallets'
    | '/auth/callback'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/account/history'
    | '/account/preferences'
    | '/account/wallets'
    | '/auth/callback'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wallets': {
      id: '/account/wallets'
      path: '/wallets'
      fullPath: '/account/wallets'
      preLoaderRoute: typeof AccountWalletsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/preferences': {
      id: '/account/preferences'
      path: '/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof AccountPreferencesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/history': {
      id: '/account/history'
      path: '/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AccountHistoryRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountHistoryRoute: typeof AccountHistoryRoute
  AccountPreferencesRoute: typeof AccountPreferencesRoute
  AccountWalletsRoute: typeof AccountWalletsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountHistoryRoute: AccountHistoryRoute,
  AccountPreferencesRoute: AccountPreferencesRoute,
  AccountWalletsRoute: AccountWalletsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
