/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as TxTransactionIdRouteImport } from './routes/tx.$transactionId'
import { Route as FxQuoteRouteImport } from './routes/fx.quote'
import { Route as FxExecuteRouteImport } from './routes/fx.execute'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AccountWalletsRouteImport } from './routes/account.wallets'
import { Route as AccountPreferencesRouteImport } from './routes/account.preferences'
import { Route as AccountHistoryRouteImport } from './routes/account.history'
import { Route as McpToolsToolNameRouteImport } from './routes/mcp.tools.$toolName'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const TxTransactionIdRoute = TxTransactionIdRouteImport.update({
  id: '/tx/$transactionId',
  path: '/tx/$transactionId',
  getParentRoute: () => rootRouteImport,
} as any)
const FxQuoteRoute = FxQuoteRouteImport.update({
  id: '/fx/quote',
  path: '/fx/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const FxExecuteRoute = FxExecuteRouteImport.update({
  id: '/fx/execute',
  path: '/fx/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWalletsRoute = AccountWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPreferencesRoute = AccountPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AccountRoute,
} as any)
const AccountHistoryRoute = AccountHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AccountRoute,
} as any)
const McpToolsToolNameRoute = McpToolsToolNameRouteImport.update({
  id: '/tools/$toolName',
  path: '/tools/$toolName',
  getParentRoute: () => McpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRouteWithChildren
  '/payment': typeof PaymentRoute
  '/stats': typeof StatsRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/fx/execute': typeof FxExecuteRoute
  '/fx/quote': typeof FxQuoteRoute
  '/tx/$transactionId': typeof TxTransactionIdRoute
  '/account/': typeof AccountIndexRoute
  '/mcp/tools/$toolName': typeof McpToolsToolNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRouteWithChildren
  '/payment': typeof PaymentRoute
  '/stats': typeof StatsRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/fx/execute': typeof FxExecuteRoute
  '/fx/quote': typeof FxQuoteRoute
  '/tx/$transactionId': typeof TxTransactionIdRoute
  '/account': typeof AccountIndexRoute
  '/mcp/tools/$toolName': typeof McpToolsToolNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRouteWithChildren
  '/payment': typeof PaymentRoute
  '/stats': typeof StatsRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/fx/execute': typeof FxExecuteRoute
  '/fx/quote': typeof FxQuoteRoute
  '/tx/$transactionId': typeof TxTransactionIdRoute
  '/account/': typeof AccountIndexRoute
  '/mcp/tools/$toolName': typeof McpToolsToolNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/mcp'
    | '/payment'
    | '/stats'
    | '/account/history'
    | '/account/preferences'
    | '/account/wallets'
    | '/auth/callback'
    | '/fx/execute'
    | '/fx/quote'
    | '/tx/$transactionId'
    | '/account/'
    | '/mcp/tools/$toolName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/payment'
    | '/stats'
    | '/account/history'
    | '/account/preferences'
    | '/account/wallets'
    | '/auth/callback'
    | '/fx/execute'
    | '/fx/quote'
    | '/tx/$transactionId'
    | '/account'
    | '/mcp/tools/$toolName'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/mcp'
    | '/payment'
    | '/stats'
    | '/account/history'
    | '/account/preferences'
    | '/account/wallets'
    | '/auth/callback'
    | '/fx/execute'
    | '/fx/quote'
    | '/tx/$transactionId'
    | '/account/'
    | '/mcp/tools/$toolName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRouteWithChildren
  PaymentRoute: typeof PaymentRoute
  StatsRoute: typeof StatsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  FxExecuteRoute: typeof FxExecuteRoute
  FxQuoteRoute: typeof FxQuoteRoute
  TxTransactionIdRoute: typeof TxTransactionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/tx/$transactionId': {
      id: '/tx/$transactionId'
      path: '/tx/$transactionId'
      fullPath: '/tx/$transactionId'
      preLoaderRoute: typeof TxTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fx/quote': {
      id: '/fx/quote'
      path: '/fx/quote'
      fullPath: '/fx/quote'
      preLoaderRoute: typeof FxQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fx/execute': {
      id: '/fx/execute'
      path: '/fx/execute'
      fullPath: '/fx/execute'
      preLoaderRoute: typeof FxExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wallets': {
      id: '/account/wallets'
      path: '/wallets'
      fullPath: '/account/wallets'
      preLoaderRoute: typeof AccountWalletsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/preferences': {
      id: '/account/preferences'
      path: '/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof AccountPreferencesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/history': {
      id: '/account/history'
      path: '/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AccountHistoryRouteImport
      parentRoute: typeof AccountRoute
    }
    '/mcp/tools/$toolName': {
      id: '/mcp/tools/$toolName'
      path: '/tools/$toolName'
      fullPath: '/mcp/tools/$toolName'
      preLoaderRoute: typeof McpToolsToolNameRouteImport
      parentRoute: typeof McpRoute
    }
  }
}

interface AccountRouteChildren {
  AccountHistoryRoute: typeof AccountHistoryRoute
  AccountPreferencesRoute: typeof AccountPreferencesRoute
  AccountWalletsRoute: typeof AccountWalletsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountHistoryRoute: AccountHistoryRoute,
  AccountPreferencesRoute: AccountPreferencesRoute,
  AccountWalletsRoute: AccountWalletsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface McpRouteChildren {
  McpToolsToolNameRoute: typeof McpToolsToolNameRoute
}

const McpRouteChildren: McpRouteChildren = {
  McpToolsToolNameRoute: McpToolsToolNameRoute,
}

const McpRouteWithChildren = McpRoute._addFileChildren(McpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRouteWithChildren,
  PaymentRoute: PaymentRoute,
  StatsRoute: StatsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  FxExecuteRoute: FxExecuteRoute,
  FxQuoteRoute: FxQuoteRoute,
  TxTransactionIdRoute: TxTransactionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
