// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
let getRequest: any
let getRequestHeader: any

async function resolveRequestHelpers(): Promise<{
  getRequest?: (() => Request)
  getRequestHeader?: ((name: string) => string | null)
}> {
  if (getRequest || getRequestHeader) {
    return {
      getRequest,
      getRequestHeader,
    }
  }

  if (typeof require !== 'undefined') {
    try {
      // Try the React Start server package first, which is the default generated import path.
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const server = require('@tanstack/react-start/server')
      getRequest = server.getRequest
      getRequestHeader = server.getRequestHeader
      return { getRequest, getRequestHeader }
    } catch {}
  }

  try {
    const module = await import('@tanstack/start-server-core')
    getRequest = module.getRequest
    getRequestHeader = module.getRequestHeader
    return { getRequest, getRequestHeader }
  } catch {}

  return { getRequest, getRequestHeader }
}

function extractAuthorizationHeader(headers: HeadersInit | undefined): string | null {
  if (!headers) return null
  if (headers instanceof Headers) {
    return headers.get('authorization') ?? headers.get('Authorization')
  }
  if (Array.isArray(headers)) {
    for (const [key, value] of headers) {
      if (key.toLowerCase() === 'authorization') {
        return value
      }
    }
    return null
  }
  if (typeof headers === 'object') {
    for (const key of Object.keys(headers)) {
      if (key.toLowerCase() === 'authorization') {
        const value = (headers as Record<string, string | string[] | undefined>)[key]
        if (typeof value === 'string') return value
        if (Array.isArray(value)) return value[0]
      }
    }
  }
  return null
}

import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async (options: any) => {
    const { next, headers } = options
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY ||
      process.env.SUPABASE_ANON_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY/SUPABASE_ANON_KEY'] : []),
      ];
      console.warn(`[Supabase Auth] Optional middleware skipped - config missing: ${missing.join(', ')}. Using Dynamic Labs auth instead.`);
      // Skip Supabase auth check and continue with Dynamic Labs auth
      return next({ context: { supabase: undefined as any, userId: "", claims: {} as any } as any });
    }

    const authHeaderFromHeaders = extractAuthorizationHeader(headers)
    const { getRequest, getRequestHeader } = await resolveRequestHelpers()

    let authHeader: string | null = null
    let authHeaderSource = ''

    if (authHeaderFromHeaders) {
      authHeader = authHeaderFromHeaders
      authHeaderSource = 'function headers'
    } else if (getRequestHeader?.('authorization')) {
      authHeader = getRequestHeader('authorization') ?? null
      authHeaderSource = 'getRequestHeader(authorization)'
    } else if (getRequestHeader?.('Authorization')) {
      authHeader = getRequestHeader('Authorization') ?? null
      authHeaderSource = 'getRequestHeader(Authorization)'
    }

    if (!authHeader) {
      const request = getRequest?.();
      authHeader = request?.headers?.get('authorization') ?? request?.headers?.get('Authorization') ?? null
      if (authHeader) {
        authHeaderSource = 'getRequest().headers'
      }

      if (!request?.headers && !authHeaderFromHeaders) {
        console.warn('[Supabase Auth] getRequest did not return a Request object or headers are unavailable', {
          hasGetRequest: typeof getRequest === 'function',
          hasGetRequestHeader: typeof getRequestHeader === 'function',
          request,
          headers: authHeaderFromHeaders ? 'present' : 'missing',
        });
      }
    }

    if (!authHeader) {
      console.warn('[Supabase Auth] No authorization header found for _serverFn auth', {
        source: authHeaderSource || 'none',
        hasHeaders: !!headers,
        hasGetRequest: typeof getRequest === 'function',
        hasGetRequestHeader: typeof getRequestHeader === 'function',
      })
      throw new Response('Unauthorized: No authorization header provided', { status: 401 });
    }

    if (process.env.NODE_ENV !== 'production') {
      console.debug('[Supabase Auth] authorization header source:', authHeaderSource)
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Response('Unauthorized: Only Bearer tokens are supported', { status: 401 });
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Response('Unauthorized: No token provided', { status: 401 });
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getUser();
    if (error || !data?.user) {
      throw new Response('Unauthorized: Invalid token', { status: 401 });
    }

    if (!data.user.id) {
      throw new Response('Unauthorized: No user ID found in token', { status: 401 });
    }

    return next({
      context: {
        supabase,
        userId: data.user.id,
        claims: {},
      },
    })
  }
)
