// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY/SUPABASE_ANON_KEY'] : []),
    ];
    console.warn(`[Supabase] Optional client not configured: ${missing.join(', ')}. Using fallback mode with Dynamic Labs auth.`);

    const fallbackAuth = {
      getSession: async () => ({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } }, error: null }),
      signOut: async () => ({ data: null, error: null }),
    };

    const noopResponse = Promise.resolve({ data: null, error: null });
    const noopFunction = () => noopResponse;
    const handler: ProxyHandler<any> = {
      get: (_, prop) => {
        if (prop === Symbol.toPrimitive) return undefined;
        if (prop === 'then') return undefined;
        return new Proxy(noopFunction, handler);
      },
      apply: () => noopResponse,
    };

    const fallbackClient = new Proxy(
      {
        auth: fallbackAuth,
        from: new Proxy(noopFunction, handler),
        channel: new Proxy(noopFunction, handler),
        rpc: new Proxy(noopFunction, handler),
        storage: new Proxy(noopFunction, handler),
      },
      {
        get: (target, prop) => {
          if (prop in target) {
            return Reflect.get(target, prop);
          }
          return new Proxy(noopFunction, handler);
        },
      }
    );

    return fallbackClient as unknown as ReturnType<typeof createClient>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;
let _supabaseAdmin: ReturnType<typeof createSupabaseClient> | undefined;

function createSupabaseAdminClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    throw new Error(
      "[Supabase] Admin client not configured: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set in the deployment environment."
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      persistSession: false,
    },
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
// Export a loosely-typed supabase client to avoid strict generated types
// blocking development when the DB types don't match local migrations.
export const supabase: any = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

export const supabaseAdmin: any = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});

