// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    console.warn(`[Supabase Admin] Optional client not configured: ${missing.join(', ')}. Using in-memory storage fallback.`);

    const noopResponse = Promise.resolve({ data: null, error: null });
    const noopFunction = () => noopResponse;
    const handler: ProxyHandler<any> = {
      get: (_, prop) => {
        if (prop === Symbol.toPrimitive) return undefined;
        if (prop === 'then') return undefined;
        return new Proxy(noopFunction, handler);
      },
      apply: () => noopResponse,
    };

    return new Proxy(
      {
        auth: new Proxy(noopFunction, handler),
        from: new Proxy(noopFunction, handler),
        rpc: new Proxy(noopFunction, handler),
      } as unknown as ReturnType<typeof createClient>,
      {
        get: (target, prop) => {
          if (prop in target) {
            return Reflect.get(target, prop);
          }
          return new Proxy(noopFunction, handler);
        },
      }
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
